export type CareerTrack='engineering'|'commercial';
export const trackNames={engineering:'Engineering & Research',commercial:'Consulting, Product & Ventures'};
export type CareerChapter={id:string;year:string;label:string;track:CareerTrack;organization:string;title:string;role:string;text:string;proof:string[];image:string;secondary?:string;href:string;book:string};
export const careerChapters:CareerChapter[]=[
 {id:'michigan',year:'2019–23',label:'Michigan',track:'engineering',organization:'University of Michigan',title:'A new place. A wider world.',role:'B.S. Materials Science & Engineering',text:'Arrived from Vietnam in 2019. Materials became devices, devices became circuits, and Michigan became a community.',proof:['Completed December 2023','Electrical Engineering minor','Summa Cum Laude'],image:'grad',href:'/about#education',book:'undergraduate'},
 {id:'materials',year:'2022',label:'Peterson Lab',track:'engineering',organization:'Peterson Lab · University of Michigan',title:'Start with the material.',role:'Undergraduate semiconductor researcher · SURE',text:'Semiconductor research involving fabrication preparation, metal contacts, annealing, and electrical characterization. The beginning of a move toward electrical engineering.',proof:['Semiconductor materials','Fabrication + characterization','Hall-effect / PPMS measurements'],image:'peterson',href:'/archive#semiconductor-characterization',book:'materials'},
 {id:'circuits',year:'2023',label:'Circuit design',track:'engineering',organization:'University of Michigan · Undergraduate IC design',title:'From devices to complete circuits.',role:'Analog, digital & VLSI team projects',text:'Voltage references, hardware-security PUFs, and digital design turned power, stability, and area into decisions a team could test.',proof:['PUF · EECS 427','Low-voltage bandgap reference','Simulation, layout & integration'],image:'puf-team',href:'/work/puf-security',book:'circuits'},
 {id:'silicon',year:'2024',label:'Faraday',track:'engineering',organization:'Faraday Technology Vietnam',title:'Real silicon.',role:'DFT / STA Engineer',text:'Worked on test and timing flows for ASIC shuttle projects, including UMC 22nm. Helped bring one project to tape-out in 1.5 months.',proof:['UMC 22nm · ASIC DFT / STA','1.5-month tape-out effort','Top-10% performance evaluation'],image:'faraday',href:'/work/faraday-tapeout',book:'real-silicon'},
 {id:'medical',year:'2024–25',label:'WICS',track:'engineering',organization:'Wireless Integrated Circuits and Systems Group (WICS)',title:'Small circuits. Demanding constraints.',role:'University of Michigan · Prof. David Wentzloff',text:'July 2024–November 2025: ultra-low-power sensor interfaces for a totally implantable auditory-prosthesis research system.',proof:['TSMC 65nm · Subthreshold analog design','Transimpedance amplifiers + active-RC filters','Noise, mismatch & PVT analysis'],image:'mackinac',href:'/work/implantable-auditory-circuits',book:'medical-technology'},
 {id:'strategy',year:'2024–26',label:'miLEAD',track:'commercial',organization:'miLEAD Consulting',title:'Give the technology a direction.',role:'Project Manager / Consultant',text:'Primary research, market analysis, and commercialization recommendations for three pre-clinical biotechnology startups, alongside my engineering work.',proof:['Three pre-clinical biotech startups','Customer + stakeholder research','Market-entry & pivot recommendations'],image:'milead',href:'/work/healthcare-commercialization',book:'strategy'},
 {id:'product',year:'2025',label:'ARTiculate',track:'commercial',organization:'Ross +Tech Innovation Jam',title:'Another way to express a feeling.',role:'Technical Architect · Team product concept',text:'Helped shape a drawing-based product concept, connecting the technical approach with the experience people would use.',proof:['Track Winner','Audience Choice','Product concept · Team achievement'],image:'articulate',href:'/work/articulate',book:'under-a-clock'},
 {id:'mhcc',year:'2025',label:'MHCC',track:'commercial',organization:'Midwest Healthcare Case Competition',title:'A recommendation people can act on.',role:'Team leader · Syntria Partners',text:'Led a historical healthcare launch recommendation connecting positioning, market access, providers, and patient support.',proof:['Semifinalist · 2025','Healthcare case competition','Historical CagriSema launch analysis'],image:'cagrisema-cover',href:'/work/cagrisema-launch-strategy',book:'under-a-clock'},
 {id:'teaching',year:'2025–26',label:'Teaching',track:'engineering',organization:'University of Michigan · EECS 215',title:'Make it understandable.',role:'Graduate Student Instructor',text:'Lectures, office hours, and circuit and amplifier laboratory materials. Helping others reason through a problem sharpened my own thinking.',proof:['400+ students supported','Introductory electronic circuits','Instruction + laboratory development'],image:'circuits-team',href:'/about#teaching',book:'teaching'},
 {id:'ntt',year:'2026',label:'NTT accelerator',track:'engineering',organization:'University of Michigan · Advanced VLSI',title:'Security, expressed in hardware.',role:'Reconfigurable accelerator · Course project',text:'A radix-2 number-theoretic-transform accelerator for post-quantum cryptography, from parallel butterfly processing and banked memory to physical implementation.',proof:['256 / 1024 polynomial sizes','Banked SRAM + DMA / FIFO integration','Synthesis + physical implementation'],image:'',href:'/archive#ntt-accelerator',book:'masters'},
 {id:'masters',year:'2026',label:'M.S. completion',track:'engineering',organization:'University of Michigan',title:'A chapter completed. A foundation carried forward.',role:'M.S. Electrical & Computer Engineering · ICs & VLSI',text:'Completed the master’s in April 2026. A graduate chapter shaped by integrated-circuit research, advanced VLSI, teaching, and the people around that work.',proof:['M.S. completed April 2026','Integrated Circuits & VLSI','Michigan commencement · 2026'],image:'masters-2026',href:'/about#education',book:'masters'},
 {id:'aurora',year:'2026',label:'Southeast Case',track:'commercial',organization:'Southeast Case Competition',title:'Choose a market. Build a route in.',role:'Team leader · Five Star Consulting',text:'A U.S. market-entry recommendation for a premium beverage, grounded in market choice, supply constraints, and staged execution.',proof:['Semifinalist · 2026','U.S. premium-beverage market entry','Competition recommendation'],image:'aurora-cover',href:'/work/aurora-market-entry',book:'under-a-clock'},
 {id:'venture',year:'2026—',label:'A Story',track:'commercial',organization:'A Story · Current convergence',title:'Begin with a conversation.',role:'Co-founder and COO',text:'Engineering rigor meets consulting judgment in a living family archive. Guided conversations preserve the stories behind the milestones.',proof:['Active development & pilots','Product experience + operations','Pilots, partnerships & commercialization'],image:'story:product-world',href:'/a-story',book:'a-story'},
];
