const originalBookChapters=[
 {id:'origin',label:'Arrival',year:'2019',title:'A place I did not know yet.',image:'portrait',paragraphs:['I arrived in Ann Arbor from Vietnam in 2019, knowing few people. Michigan was a place to study before it became the place where much of my life took shape.','Courses became projects. Projects became teams. The unfamiliar city acquired familiar faces, and eventually the feeling of home.','There was no plan that connected every chapter in advance. I followed what I was learning, and the path grew from there.'],link:'/about',linkLabel:'More about Bao'},
 {id:'materials',label:'Peterson Lab',year:'2022',title:'Start with what is real.',image:'peterson',paragraphs:['My early research involved semiconductor thin films: depositing metal contacts, annealing samples, and studying their electrical behavior.','At Peterson Lab, materials science became a practical discipline. Prepare a sample. Take a measurement. Change a condition. Look again.','That sequence still informs how I think. An explanation needs to survive contact with the thing it describes.'],link:'/archive#semiconductor-characterization',linkLabel:'The research record'},
 {id:'circuits',label:'Circuits',year:'2023',title:'Every improvement asks for something.',image:'puf-team',paragraphs:['Circuit design made constraints tangible. Lower power, greater gain, faster operation, and less area could not all be independent wishes.','The projects ranged from amplifiers and arithmetic circuits to voltage references and hardware security. One explored whether device variation could become a dependable chip identity. Another asked how to hold a voltage steady as conditions changed.','The most interesting part was often the limit that refused to go away.'],link:'/work/puf-security',linkLabel:'Variation as identity'},
 {id:'undergraduate',label:'Undergraduate completion',year:'2023',title:'A foundation, and a wider view.',image:'grad',paragraphs:['I completed my B.S. in Materials Science and Engineering in December 2023, with an Electrical Engineering minor and Summa Cum Laude honors.','Materials gave me a starting point. Analog and digital circuit projects made me want to keep following the question into complete systems.'],link:'/about#education',linkLabel:'Education at Michigan'},
 {id:'real-silicon',label:'Faraday',year:'2024',title:'Eventually, someone has to sign off.',image:'faraday',paragraphs:['At Faraday Technology Vietnam, the work had a fabrication deadline. My part was chip-level test and timing: insertion, simulation, tester patterns, and sign-off.','I helped bring a shuttle project to tape-out within 1.5 months. The pace made coordination concrete. A detail mattered when it arrived in a form the next person could use.','The design mattered. So did the handoff.'],link:'/work/faraday-tapeout',linkLabel:'The Faraday chapter'},
 {id:'medical-technology',label:'WICS',year:'2024–25',title:'What happens beyond the lab?',image:'mackinac',paragraphs:['From July 2024 to November 2025, my research in the Wireless Integrated Circuits and Systems Group (WICS), with Prof. David Wentzloff, focused on low-power circuits for an implantable auditory prosthesis. I developed interfaces, amplifiers, and filters, and evaluated their behavior across operating conditions.','The circuit questions were demanding. Increasingly, I wanted to understand the path beyond them: how a device would be made, used, adopted, and supported.','That curiosity became a reason to explore commercialization.'],link:'/work/implantable-auditory-circuits',linkLabel:'The research chapter'},
 {id:'teaching',label:'Teaching / EECS 215',year:'2025–26',title:'Make it understandable.',image:'lake',paragraphs:['As a Graduate Student Instructor, I lectured, held office hours, and helped develop laboratory materials for introductory electronic circuits. The course supported more than 400 students.','Teaching required a different precision. Being correct was a starting point; an explanation also had to connect with the person hearing it.','I want to carry that habit into product and strategy: checking whether an explanation has actually made the next step clearer.'],link:'/about#teaching',linkLabel:'Teaching at Michigan'},
 {id:'strategy',label:'miLEAD',year:'2024–26',title:'The frame gets wider.',image:'milead',paragraphs:['At miLEAD, a recommendation had to account for customers, competitors, pricing, and the capabilities of an early-stage life-science team.','I worked on primary research and market-entry or pivot recommendations. An attractive technology did not, by itself, identify the market it should enter.','The task was to turn evidence into a position leadership could examine and act on. I was learning to keep more of the surrounding system in view.'],link:'/work/healthcare-commercialization',linkLabel:'The consulting chapter'},
 {id:'under-a-clock',label:'Under a clock',year:'2025–26',title:'Make the recommendation clear.',image:'articulate',paragraphs:['Competitions compressed the process: form a team, choose a direction, build a case, and explain it before time ran out.','ARTiculate explored guided drawing and emotional expression. Other teams I led developed recommendations for a healthcare launch and a U.S. beverage-market entry.','The results included a Ross +Tech Innovation Jam track win, Audience Choice, and semifinal placements at MHCC and SECC. The lasting practice was deciding what an audience needed to understand first.'],link:'/work/articulate',linkLabel:'ARTiculate and the team'},
 {id:'michigan',label:'Community',year:'Beyond the work',title:'A place becomes people.',image:'visa',paragraphs:['Michigan also means cultural nights, time with friends, and days when the work can wait.','I co-founded the Vietnamese International Student Association because a new place is easier to enter when a community is ready to welcome you. I wanted the next students from Vietnam to have a better start.','The photographs from these years are full of other people. That feels like an honest account of how a place became home.'],link:'/about#community',linkLabel:'The community chapter'},
 {id:'personal',label:'Off the clock',year:'Beyond the work',title:'A little distance helps.',image:'skiing',paragraphs:['Skiing in the Wasatch Mountains. Time above Devil’s Lake. A poker table with friends. Not every good day needs to produce something.','These moments give the work a different perspective, and keep the years from becoming only a list of projects.'],link:'/about#outside',linkLabel:'Outside the formal record'},
 {id:'masters',label:'Master’s',year:'2026',title:'The work happened among people.',image:'masters-2026',paragraphs:['I completed my M.S. in Electrical and Computer Engineering, focused on Integrated Circuits and VLSI, in April 2026.','The technical development happened inside a community: researchers, mentors, classmates, and collaborators. The stadium photograph holds that chapter better than a credential alone could.'],link:'/about#research',linkLabel:'The graduate research chapter'},
 {id:'why-a-story',label:'Product / a new focus',year:'2026',title:'What do we remember to keep?',image:'flatlay',paragraphs:['A Story brings technical and human questions into the same experience.','The archive has to make sense to a person telling a memory and to a relative helping preserve it. A clear flow matters. So does the feeling that an account still belongs to the person who told it.','Engineering taught me rigor. Strategy taught me context. This is a problem where both matter, and where I want to spend my time now.'],link:'/a-story#my-role',linkLabel:'Why I’m building A Story'},
 {id:'a-story',label:'A Story',year:'2026—',title:'Begin with one conversation.',image:'keepsake',paragraphs:['We are building a family archive that grows through conversations, photographs, and contributions from relatives.','As Co-founder and COO, my focus is product strategy, operations, and pilot development. Work in nursing-home settings helps us test and refine the experience.','There is a longer vision for what an archive might become, including a possible printed keepsake. We are starting earlier: with a first memory that gives someone a reason to return.'],link:'/a-story',linkLabel:'Explore A Story'},
 {id:'next-chapter',label:'What comes next',year:'Still being written',title:'There is more to figure out.',image:'mackinac',paragraphs:['I’m interested in ambitious products, difficult technology, and the strategy that turns one into the other.','The next chapter does not need to look like the last one. It does need to be worth doing.','If you are working on something that needs both technical and commercial judgment, I would be glad to hear about it.'],link:'/contact',linkLabel:'Start a conversation'},
];

/**
 * The page text of each chapter, set as a book rather than a summary card:
 * two short paragraphs (the first opens with a drop cap) and a closing line
 * that is never a repeat of the chapter title. The same text is used by the
 * page view, the scrolling view and the no-JS reading, so there is one
 * version of the book. Facts come from the chapters above, the case pages and
 * the résumé-sourced copy; nothing here is new information.
 */
const pages:Record<string,{prose:string[];coda:string}>={
 origin:{prose:['I arrived in Ann Arbor from Vietnam in 2019, knowing few people. Michigan was a place to study before it became the place where much of my life took shape.','Courses became projects. Projects became teams. The unfamiliar city acquired familiar faces, and eventually the feeling of home.'],coda:'There was no plan that connected every chapter in advance. The path grew from what I was learning.'},
 materials:{prose:['My early research at Peterson Lab involved semiconductor thin films: depositing metal contacts, annealing samples, and studying their electrical behavior.','Materials science became a practical discipline. Prepare a sample. Take a measurement. Change a condition. Look again.'],coda:'An explanation needs to survive contact with the thing it describes.'},
 circuits:{prose:['Circuit design made constraints tangible. Lower power, greater gain, faster operation and less area could not all be independent wishes.','The projects ran from amplifiers and arithmetic circuits to voltage references and hardware security; one asked whether device variation could become a dependable chip identity. That December I completed my B.S. in Materials Science and Engineering, with an Electrical Engineering minor, Summa Cum Laude.'],coda:'The most interesting part was often the limit that refused to go away.'},
 'real-silicon':{prose:['At Faraday Technology Vietnam, the work had a fabrication deadline. My part was chip-level test and timing for ASIC shuttle projects, including UMC 22nm: insertion, simulation, tester patterns and sign-off.','I helped bring one shuttle project to tape-out within 1.5 months. The pace made coordination concrete. A detail mattered when it arrived in a form the next person could use.'],coda:'The design mattered. So did the handoff.'},
 'medical-technology':{prose:['From July 2024 to November 2025, in the Wireless Integrated Circuits and Systems Group with Prof. David Wentzloff, I worked on low-power circuits for a totally implantable auditory prosthesis: sensor interfaces, amplifiers, active-RC filters and MEMS/ASIC interfaces in TSMC 65nm.','The circuit questions were demanding. Increasingly, I wanted to understand the path beyond them: how a device would be made, used, adopted and supported.'],coda:'That curiosity became a reason to explore commercialization.'},
 strategy:{prose:['At miLEAD, I combined primary research, commercial analysis and project management for three pre-clinical biotech startups. A recommendation had to account for customers, competitors, pricing and what an early team could actually do.','An attractive technology did not, by itself, identify the market it should enter. Our market-entry and pivot recommendations went directly to leadership teams.'],coda:'The work was turning evidence into a position someone could act on.'},
 'under-a-clock':{prose:['Competitions compressed the whole process: form a team, choose a direction, build a case, and explain it before time ran out.','As Technical Architect for ARTiculate, a drawing-led product concept, our team earned Track Winner and Audience Choice at the Ross +Tech Innovation Jam. I also led semifinalist teams at MHCC and the Southeast Case Competition.'],coda:'The lasting practice was deciding what an audience needed to understand first.'},
 michigan:{prose:['I co-founded the Vietnamese International Student Association because a new place is easier to enter when a community is ready to welcome you. I wanted the next students from Vietnam to have a better start.','As a Graduate Student Instructor for EECS 215, I lectured, held office hours and helped develop laboratory materials for a course serving more than 400 students. Being correct was a starting point; an explanation also had to connect.'],coda:'The photographs from these years are full of other people. That feels like an honest account of how a place became home.'},
 masters:{prose:['I completed my M.S. in Electrical and Computer Engineering, focused on Integrated Circuits and VLSI, in April 2026.','The technical development happened inside a community: researchers, mentors, classmates and collaborators. Research, advanced VLSI, teaching and community shaped the chapter together.'],coda:'The stadium photograph holds this chapter better than a credential alone could.'},
 'a-story':{prose:['Most of a life goes undocumented. The milestones usually survive; the everyday slips away quietly, because nobody thought to ask.','A Story calls someone you love, listens, and follows up the way someone who knows them would. What they say becomes a private archive the whole family can add to. As Co-founder and COO, my focus is product strategy, operations and pilot development.'],coda:'Not a memoir to finish. A Story to keep, and to carry on.'},
 personal:{prose:['Skiing in the Wasatch Mountains. Time above Devil’s Lake. A poker table with friends in Las Vegas.','Not every good day needs to produce something. These moments give the work a different perspective.'],coda:'They keep the years from becoming only a list of projects.'},
 'next-chapter':{prose:['My interest is in ambitious products, difficult technology, and the strategy that turns one into the other.','The next chapter does not need to look like the last one. It does need to be worth doing.'],coda:'If you are working on something that needs both technical and commercial judgment, I would be glad to hear about it.'},
};
const WORDS=['One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve'];

export const bookChapterAliases:Record<string,string>={undergraduate:"circuits",teaching:"michigan","why-a-story":"a-story"};
export const bookChapters=["origin","materials","circuits","real-silicon","medical-technology","strategy","under-a-clock","michigan","masters","a-story","personal","next-chapter"].map((id,i)=>({...originalBookChapters.find(c=>c.id===id)!,...pages[id],word:WORDS[i]}));
