export const evidence:Record<string,{image?:string;links:[string,string][];note:string;team?:string}>={
 'faraday-tapeout':{links:[['Director’s testimonial · April 2026 (PDF)','/documents/faraday-testimonial-bao-vo.pdf']],note:'The 1.5-month figure describes a shuttle project’s tape-out timeline, not total employment. Internal customer layouts and test patterns are not displayed.'},
 'implantable-auditory-circuits':{links:[['Engineering résumé (PDF)','/documents/bao-vo-engineering-resume.pdf']],note:'Circuit development and simulation for a research system.'},
 'healthcare-commercialization':{links:[['Business résumé (PDF)','/documents/bao-vo-business-resume.pdf']],note:'Client work is summarized publicly; confidential deliverables are not shown.'},
 articulate:{image:'articulate-detail',links:[['Selected concept deck excerpts (PDF)','/documents/articulate-selected-excerpts.pdf']],note:'Competition product concept · Track Winner and Audience Choice.',team:'Ashita Nichanametla, Hao Liu, Linh Tran, Bao Vo, Danika Lau and Kemi Orisile.'},
 'aurora-market-entry':{image:'aurora-cover',links:[['Selected competition excerpts (PDF)','/documents/aurora-selected-excerpts.pdf']],note:'SECC 2026 semifinalist. Selected excerpts present the team’s competition recommendation.',team:'Bao Vo, Shiuan-Bai Ann, Wendi Ma, Bide Chen and Yueheng Xing.'},
 'cagrisema-launch-strategy':{image:'cagrisema-detail',links:[['Selected competition excerpts (PDF)','/documents/cagrisema-selected-excerpts.pdf']],note:'MHCC 2025 semifinalist. The preserved deck is the quarterfinal submission.',team:'Bao Vo, Shiuan-Bai Ann, Jane Tang and Yulu Peng.'},
 'puf-security':{image:'puf-cover',links:[['Final report (PDF)','/documents/puf-final-report.pdf'],['Related presentation (PDF)','/documents/puf-final-presentation.pdf']],note:'The report compares 95% ring-oscillator and approximately 10% SRAM yield in simulation. The presentation reports a different SRAM figure and area; these are separate source versions, not fabrication-yield claims.',team:'Yeshas Gowda, Rahul Narasimhegowda, Avinash Gupta, Bao Vo, Ali Hammoud and Alex Knowlton.'},
 'low-voltage-bandgap':{image:'bandgap-cover',links:[['Course report · Results pp. 4–5 (PDF)','/documents/low-voltage-bandgap-reference-report.pdf']],note:'The reported 13.14 ppm/°C result is simulated at 1.2 V over 0–70°C. The abstract and later results contain inconsistencies; the results section is the source for this statement.',team:'Alan Maier, Bao Vo, Richard Wan and Amanda Whitley.'},
};
