export const projects=[
 {slug:'a-story',title:'A Story',year:'2026—',category:'Product / Venture',role:'Co-founder and COO',note:'A family archive, built through conversation.',image:'keepsake',href:'/a-story',status:'Active development & pilots'},
 {slug:'healthcare-commercialization',title:'Healthcare commercialization',year:'2024–26',category:'Consulting',role:'Project Manager / Consultant · miLEAD',note:'Turning life-science research into a considered market direction.',image:'milead',href:'/work/healthcare-commercialization',status:'Consulting · Public summary'},
 {slug:'faraday-tapeout',title:'From design to tape-out',year:'2024',category:'Engineering',role:'DFT/STA Engineer · Faraday Technology',note:'Test, timing, and the discipline of getting silicon out the door.',image:'faraday',href:'/work/faraday-tapeout',status:'Industry engineering'},
 {slug:'implantable-auditory-circuits',title:'Circuits for an implantable device',year:'2024–25',category:'Research',role:'Graduate Student Researcher · Michigan',note:'Low-power circuit research with a much larger human purpose.',image:'mackinac',href:'/work/implantable-auditory-circuits',status:'Research · Circuit simulation'},
 {slug:'articulate',title:'ARTiculate',year:'2025',category:'Product',role:'Technical Architect · Team project',note:'Exploring drawing as another way to express a feeling.',image:'articulate',href:'/work/articulate',status:'Product concept · Track winner'},
 {slug:'aurora-market-entry',title:'Aurora: a route into the U.S.',year:'2026',category:'Case competition',role:'Team leader · Five Star Consulting',note:'Market choice, supply constraints, and a staged entry recommendation.',image:'aurora-cover',href:'/work/aurora-market-entry',status:'Competition · Semifinalist'},
 {slug:'cagrisema-launch-strategy',title:'CagriSema launch strategy',year:'2025',category:'Healthcare case',role:'Team leader · Syntria Partners',note:'Connecting positioning with access, providers, and patient support.',image:'cagrisema-cover',href:'/work/cagrisema-launch-strategy',status:'Historical competition · Semifinalist'},
 {slug:'puf-security',title:'Variation as identity',year:'2023',category:'Engineering',role:'Team contributor · EECS 427',note:'Comparing two approaches to a dependable hardware identity.',image:'puf-team',href:'/work/puf-security',status:'Course project · Simulation and layout'},
 {slug:'low-voltage-bandgap',title:'A reference under constraints',year:'2023',category:'Engineering',role:'Team contributor · Circuit coursework',note:'Power, stability, and the compromises behind a voltage reference.',image:'bandgap-detail',href:'/work/low-voltage-bandgap',status:'Course project · Simulation and layout'},
];
export const extras=[
 {slug:'ntt-accelerator',title:'NTT accelerator for post-quantum cryptography',year:'2026',category:'Engineering',note:'A reconfigurable radix-2 NTT accelerator for polynomial sizes 256 and 1024: parallel butterfly processing, banked SRAM, DMA/FIFO integration, synthesis and physical implementation.',status:'Course project · Résumé-documented',href:'/documents/bao-vo-engineering-resume.pdf',image:''},
 {slug:'teaching',title:'Teaching introductory electronic circuits',year:'2025–26',category:'Teaching',note:'Lectures, office hours, and circuit and amplifier laboratory material for EECS 215 at Michigan, supporting instruction for more than 400 students.',status:'Graduate Student Instructor',href:'/about#teaching',image:''},
 {slug:'rf-front-end',title:'Quadrature mixer-first RF front end',year:'2023',category:'Research',note:'Quadrature clock generation and a mixer-first receiver in TSMC 65nm, including a Windmill divider and analysis of conversion gain, power, and phase-noise behavior.',status:'Research / design · Résumé-documented',href:'/documents/engineering-project-history.pdf',image:''},
 {slug:'amplifier-studies',title:'Amplifier design studies',year:'2023',category:'Engineering',note:'Two studies: a three-stage bipolar-transistor amplifier for a bandpass-filter exercise, and a low-input/output-impedance multistage amplifier with dual gain modes.',status:'Circuit coursework · Résumé-documented',href:'/documents/engineering-project-history.pdf',image:''},
 {slug:'ripple-carry-adder',title:'Dual-mode ripple-carry adder',year:'2023',category:'Engineering',note:'An 8-bit ripple-carry adder explored through separate power and speed optimizations. The design exercise is documented in the engineering project history.',status:'Circuit coursework · Résumé-documented',href:'/documents/engineering-project-history.pdf',image:''},
 {slug:'energy-harvesting',title:'Energy-harvesting sensor hardware',year:'2022–23',category:'Engineering',note:'Electrical characterization of a sensor board, C-based monitoring, and a portable application board designed around the sensor’s power profile with an integrated harvesting device.',status:'Hardware project · Résumé-documented',href:'/documents/engineering-project-history.pdf',image:''},
 {slug:'semiconductor-characterization',title:'Ultra-wide-bandgap semiconductor characterization',year:'2022',category:'Research',note:'Metal-contact deposition, annealing, and electrical characterization of semiconductor thin films through cleanroom fabrication and Hall-effect/PPMS measurements.',status:'Peterson Lab / SURE · Undergraduate research',href:'/documents/engineering-project-history.pdf',image:'peterson'},
 {slug:'visa',title:'Vietnamese International Student Association',year:'Undated',category:'Community',note:'Co-founding a community for Vietnamese international students at Michigan. Helping new arrivals find a welcome in Ann Arbor.',status:'Co-founder · Community',href:'/about#community',image:'visa'},
 {slug:'off-the-clock',title:'Off the clock',year:'Undated',category:'Personal',note:'Soccer, poker, the batting cage, and time outdoors. A life in Michigan beyond the résumé.',status:'Personal photographs',href:'/about#outside',image:'poker'},
 {slug:'michigan',title:'Michigan, beyond the classroom',year:'2019—',category:'Community',note:'From arrival in Ann Arbor to graduation, lab trips, cultural events, and the people who made Michigan home.',status:'Personal record',href:'/about',image:'mackinac'},
];
export const chronology=[
 {year:'2019',title:'A new place.',label:'Vietnam → Michigan',text:'I arrived in Ann Arbor to study at the University of Michigan. It would become the place where I built, taught, competed, and found community.',href:'/book?chapter=origin&mode=pages'},
 {year:'2022',title:'Start with the material.',label:'Materials / research',text:'Semiconductor characterization at Peterson Lab, through Michigan’s SURE program. A foundation in making, measuring, and testing assumptions.',href:'/archive#semiconductor-characterization'},
 {year:'2023–24',title:'Make it hold up.',label:'Circuits / silicon',text:'Circuit projects and a materials science degree with an electrical engineering minor, followed by chip-level test and timing at Faraday Technology Vietnam.',href:'/work/faraday-tapeout'},
 {year:'2024–25',title:'Look beyond the device.',label:'Medical technology / commercialization',text:'Low-power circuits for an implantable auditory prosthesis, alongside a growing interest in life-science markets and adoption.',href:'/work/implantable-auditory-circuits'},
 {year:'2025–26',title:'Widen the frame.',label:'Strategy / teaching / product',text:'miLEAD consulting, teaching EECS 215, and team competitions in product development and commercial strategy. Different settings, more of the surrounding system in view.',href:'/work'},
 {year:'2026—',title:'Begin with a conversation.',label:'A Story / current venture',text:'Co-founding A Story. Developing a family archive and learning through pilots, with product strategy and operations as my focus.',href:'/a-story'},
];
