'use client';
import {useEffect,useMemo,useState} from 'react';import {projects,extras} from '@/content/projects';import {evidence} from '@/content/evidence';import {ArrowLink,Photo} from './Ledger';
const records=[...projects,...extras];const categories=[...new Set(records.map(r=>r.category))];
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const yearOf=(s:string)=>s==='Undated'?0:s.includes('–')?Number(s.split('–')[1].length===2?'20'+s.split('–')[1]:s.slice(0,4)):Number(s.slice(0,4));
export function ArchiveIndex({initialQuery='',initialCategory='',initialYear='',initialSort='newest'}:{initialQuery?:string;initialCategory?:string;initialYear?:string;initialSort?:string}){
 const [query,setQuery]=useState(initialQuery);const [category,setCategory]=useState(initialCategory);const [year,setYear]=useState(initialYear);const [sort,setSort]=useState(initialSort);const [notice,setNotice]=useState('');
 function write(q:string,c:string,y:string,s:string,push=false){const params=new URLSearchParams();if(q)params.set('q',q);if(c)params.set('category',c);if(y)params.set('year',y);if(s!=='newest')params.set('sort',s);const target=`/archive${params.size?'?'+params:''}`;if(push)history.pushState(null,'',target);else history.replaceState(null,'',target)}
 useEffect(()=>{const restore=()=>{const p=new URLSearchParams(location.search);setQuery(p.get('q')||'');setCategory(p.get('category')||p.get('discipline')||'');setYear(p.get('year')||'');setSort(p.get('sort')||'newest')};const reveal=()=>{const id=decodeURIComponent(location.hash.slice(1));if(!records.some(r=>r.slug===id))return;setQuery('');setCategory('');setYear('');setNotice('Showing the linked record. Filters have been cleared.');requestAnimationFrame(()=>{const el=document.getElementById(id) as HTMLDetailsElement|null;if(el){el.open=true;el.scrollIntoView()}})};reveal();window.addEventListener('popstate',restore);window.addEventListener('hashchange',reveal);return()=>{window.removeEventListener('popstate',restore);window.removeEventListener('hashchange',reveal)}},[]);
 const result=useMemo(()=>records.filter(r=>(!category||normalize(r.category)===normalize(category))&&(!year||r.year.includes(year)||String(yearOf(r.year))===year)&&normalize(`${r.slug} ${r.title} ${r.note} ${r.status} ${r.category}`).includes(normalize(query))).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):((yearOf(a.year)||-999)-(yearOf(b.year)||-999))*(sort==='oldest'?1:-1)),[query,category,year,sort]);
 function clear(){setQuery('');setCategory('');setYear('');setSort('newest');setNotice('');write('','','','newest',true)}
 return <div className="archive-index container"><form className="archive-controls" action="/archive" onSubmit={e=>{e.preventDefault();write(query,category,year,sort,true)}}><label className="archive-search">Search the Archive<input type="search" name="q" placeholder="Projects, tools, topics…" value={query} onChange={e=>{setQuery(e.target.value);write(e.target.value,category,year,sort)}}/></label><label>Discipline<select aria-label="Discipline" name="category" value={category} onChange={e=>{setCategory(e.target.value);write(query,e.target.value,year,sort,true)}}><option value="">All disciplines</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Year<select aria-label="Year" name="year" value={year} onChange={e=>{setYear(e.target.value);write(query,category,e.target.value,sort,true)}}><option value="">All years</option>{['2026','2025','2024','2023','2022','2019','Undated'].map(y=><option key={y}>{y}</option>)}</select></label><label>Order<select aria-label="Order" name="sort" value={sort} onChange={e=>{setSort(e.target.value);write(query,category,year,e.target.value,true)}}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="title">Title A–Z</option></select></label><button type="submit">Search</button></form><div className="archive-results-line"><p aria-live="polite">{result.length} {result.length===1?'record':'records'}<span> / Select a row to open its record</span></p><button onClick={clear}>Clear filters</button></div>{notice&&<p className="small" role="status">{notice}</p>}
 <div className="archive-records">{result.map((r,i)=><details key={r.slug} id={r.slug} className="archive-record"><summary><span className="record-num">{String(i+1).padStart(2,'0')}</span><span className="record-year">{r.year}</span><span className="record-title">{r.title}</span><span className="record-category">{r.category}</span><span className="record-toggle" aria-hidden="true"/></summary><div className="record-content"><div><p className="eyebrow">{r.status}</p><p>{r.note}</p>{evidence[r.slug]&&<p className="small">{evidence[r.slug].note}</p>}<ArrowLink href={r.href}>{r.href.endsWith('.pdf')?'Read the source résumé (PDF)':'Explore this chapter'}</ArrowLink>{evidence[r.slug]?.links.map(([label,href])=><a className="record-document" href={href} key={href}>{label}</a>)}<a className="record-permalink" href={`#${r.slug}`}>Link to this record</a></div>{r.image?<Photo id={r.image} sizes="(max-width:767px) 85vw, 30vw"/>:<div className="record-text-exhibit"><span className="small">PROJECT RECORD</span><h3>{r.title}</h3><span className="small">{r.year} / {r.category}</span></div>}</div></details>)}</div>{result.length===0&&<div className="archive-empty"><h2>No records match.</h2><p>Try a broader phrase or remove a filter.</p><button onClick={clear}>Clear filters</button></div>}
 <div className="archive-source-note"><h2>The material behind the index.</h2><p>This index includes the early projects as well as the current ones. Public reports and selected competition excerpts are linked in their records, alongside the people and context behind the work.</p><div className="artifact-links"><ArrowLink href="/documents/bao-vo-business-resume.pdf">Business résumé (PDF)</ArrowLink><ArrowLink href="/documents/bao-vo-engineering-resume.pdf">Engineering résumé (PDF)</ArrowLink><ArrowLink href="/documents/engineering-project-history.pdf">Early engineering project history (PDF)</ArrowLink></div></div>
 </div>
}


