import {ArrowLink,ContactClose,Label,Photo} from './Ledger';
import {ChapterNav,Timeline,WorkIndex} from './Discovery';
import {BookReader} from './BookReader';
import {StoryShowcase} from './StoryShowcase';
import {AtGlance} from './AtGlance';
import {StoryBrand} from './StoryBrand';
import {HomeEntrance} from './HomeEntrance';
import {story} from '@/content/story';

export function Venture(){return <section id="current-venture" className="new-venture"><div className="container"><div className="venture-kicker"><Label num="03">The venture I’m building now</Label><a className="status-tag st-site" href={story.site}><i/>{story.siteLabel} · Waitlist open <span aria-hidden="true">↗</span></a></div><div className="venture-feature"><div className="venture-intro"><StoryBrand/><h2>Most of a life<br/>goes undocumented.</h2><p><strong>A Story calls someone you love, listens, and follows up the way someone who knows them would.</strong> What they say becomes a private archive the whole family can add to.</p><p className="venture-brandline">Not a memoir to finish.<br/>A Story to keep, and to carry on.</p><div className="st-actions"><ArrowLink className="solid-link" href="/a-story">See how A Story works</ArrowLink><ArrowLink href={story.site}>Visit {story.siteLabel}</ArrowLink></div><div className="venture-credit"><span>BAO’S ROLE</span><strong>Co-founder and COO</strong></div></div><StoryShowcase compact/></div><div className="venture-principles">{story.steps.map(s=><div key={s.n}><b>{s.n} / {s.who.toUpperCase()}</b><p>{s.title} {s.text.split('. ')[0]}.</p></div>)}</div></div></section>}

export function Home({variant='b'}:{variant?:string}){return <main id="main" className="new-home" data-entrance="motion"><HomeEntrance/>
 <section id="overview" className={`identity-hero ${variant==='a'?'rectangular-hero':''}`}><div className="container"><div className="identity-layout"><div className="identity-copy"><Label><span className="sparkle" aria-hidden="true">✦</span> Founder · Strategist · Builder</Label><p className="hello-line">Hi, I’m Bao Vo.</p><h1><span>From silicon</span><span>to <em>strategy.</em></span></h1><p className="identity-description">I build products, shape strategy, and turn difficult technology into something that matters to people.</p><div className="identity-actions"><ArrowLink href="#timeline" className="solid-link">Explore the path</ArrowLink><ArrowLink href="#the-book" className="outline-link">Open the flipbook</ArrowLink></div><a className="hero-discovery" href="#selected-work">Discover the work <span aria-hidden="true">↓</span></a><div className="current-note"><span className="live-dot"/><div><span className="small">THE CURRENT CHAPTER</span><p>Co-founding <a href="/a-story">A Story</a>, from Michigan.</p></div></div></div><div className="identity-image"><div className="arch-frame"><Photo id="portrait" caption={false} priority sizes="(max-width:767px) 88vw, 42vw"/></div><div className="identity-caption"><span>Bao Vo<span className="gold">.</span></span><span>Ann Arbor, Michigan</span></div></div></div></div></section>
 <ChapterNav/>
 <section id="timeline" className="journey-section section"><div className="container"><Label num="01">The path so far</Label><div className="section-heading"><h2>How the<br/><em>chapters connect.</em></h2><p>A connected chronology of places, people, and work. Follow a year to see how one chapter opened the next.</p></div><Timeline/></div></section>
 <section id="the-book" className="home-book-section"><div className="container book-section-heading"><div><Label num="02">Two ways through the story</Label><h2>Scan the years.<br/><em>Or turn the pages.</em></h2></div><p>The Book is a more personal way<br/>through the same path.</p></div><BookReader embedded/></section>
 <Venture/>

 <section id="selected-work" className="section container"><Label num="05">Selected work</Label><div className="section-heading"><h2>Make it work.<br/><em>Make it matter.</em></h2><p>Explore the teams, decisions, and artifacts behind the work. Choose a chapter to take a closer look.</p></div><WorkIndex lenses/><div className="section-end"><ArrowLink href="/work" className="outline-link">All selected work</ArrowLink></div></section>
 <AtGlance/>
 <section id="recognition" className="recognition blue section"><div className="container"><Label>Recognition · Good work is a team sport.</Label><div className="recognition-grid"><div><span className="quote-ornament" aria-hidden="true">“</span><blockquote>His performance has consistently been in the <em>Top 10%.</em></blockquote><p className="quote-credit">Raymond Nguyen<br/><span>Director, Faraday Technology Vietnam · April 2026</span></p><ArrowLink href="/documents/faraday-testimonial-bao-vo.pdf">Read the director’s testimonial (PDF)</ArrowLink></div><div className="recognition-photo"><Photo id="award" sizes="(max-width:767px) 85vw, 36vw"/><span className="award-sticker">Audience Choice<br/><b>+Tech Innovation Jam</b></span></div></div><div className="recognition-records"><a href="/work/articulate"><b>Track winner</b><span>Ross +Tech Innovation Jam · ARTiculate ↗</span></a><a href="/work/cagrisema-launch-strategy"><b>Semifinalist</b><span>Midwest Healthcare Case Competition · 2025 ↗</span></a><a href="/work/aurora-market-entry"><b>Semifinalist</b><span>Southeast Case Competition · 2026 ↗</span></a></div></div></section>
 <section id="archive" className="complete-archive section container"><div><Label num="07">The complete archive</Label><h2>There’s more<br/><em>on the record.</em></h2><p>The experiments, reports, early ideas, and community work that don’t fit into a highlight reel.</p><ArrowLink href="/archive" className="solid-link">Explore the full archive</ArrowLink></div><div className="archive-cards"><a href="/work/puf-security"><Photo id="puf-cover" caption={false}/><span>01 / Engineering & research ↗</span></a><a href="/work/aurora-market-entry"><Photo id="aurora-cover" caption={false}/><span>02 / Consulting & commercialization ↗</span></a><a href="/work/articulate"><Photo id="articulate-cover" caption={false}/><span>03 / Product & ventures ↗</span></a></div></section>
 <section id="off-the-clock" className="off-clock section"><div className="container"><div className="off-copy"><Label num="08">Off the clock</Label><h2>Reading<br/><em>the room.</em></h2><p>Sports taught me competition. Poker taught me incomplete information. Community gave Michigan the feeling of home.</p><p>I arrived from Vietnam in 2019 knowing few people. Later, I co-founded VISA so that the next students would find a community waiting.</p><ArrowLink href="/about#outside" className="outline-link">Beyond the résumé</ArrowLink></div><div className="personal-grid"><Photo id="poker"/><Photo id="skiing"/><Photo id="visa"/><Photo id="lake"/></div></div></section>
 <ContactClose/>
 </main>}
