'use client';
import {useState} from 'react';
import {demoMemory,demoVoices} from '@/content/story-demo';
const panels=[
 {id:'home',label:'Everyday memories',title:'A place to return to.',copy:'A daily invitation. A recent memory. Something a relative added. The archive begins in ordinary life.'},
 {id:'conversation',label:'Conversation',title:'A question becomes a conversation.',copy:'Start with something familiar. Follow the detail that only this person could remember.'},
 {id:'timeline',label:'Living timeline',title:'Today belongs here, too.',copy:'Connect the years without leaving out the present. The next family memory is still being made.'},
 {id:'perspectives',label:'Many perspectives',title:'One event. More than one account.',copy:'People, photographs, and separate recollections attach to the same memory. Every voice keeps its place.'},
 {id:'book',label:'Something to keep',title:'Something to carry on.',copy:'A growing archive can become a tangible keepsake: photographs, moments, and the voices behind them.'}
];
function ContextCard({id}:{id:string}){return <aside className={'theater-artifact artifact-'+id} aria-label="Example memory context">
 {id==='home'&&<><img src={demoMemory.image} alt="A table set for the example Sunday meal" width="1200" height="900"/><span className="small">RECENT MEMORY</span><h4>{demoMemory.title}</h4><p>Eleanor’s story. A detail from Daniel.</p></>}
 {id==='conversation'&&<><span className="small">A FOLLOW-UP, NOT A SCRIPT</span><h4>Who always arrived last?</h4><div className="theater-wave" aria-hidden="true">▂ ▅ ▃ ▆ ▄ ▂ ▇ ▅ ▃ ▆ ▂</div><p>“We kept the dishes warm. Daniel would bring another chair.”</p><span className="small">Eleanor · Original account</span></>}
 {id==='timeline'&&<><span className="small">A LIVING RECORD</span><div className="theater-timeline"><p><b>1998–99</b>{demoMemory.title}</p><p><b>Today</b>Maya adds the corner-seat memory.</p><p><b>Still to come</b>The next Sunday together.</p></div></>}
 {id==='perspectives'&&<><span className="small">ONE CONNECTED MEMORY</span><h4>{demoMemory.title}</h4><div className="theater-people">{demoVoices.map(v=><p key={v.name}><strong>{v.name}</strong><span>{v.detail}</span></p>)}</div><p className="small">Three accounts, kept together.</p></>}
 {id==='book'&&<><img src={demoMemory.image} alt="The Sunday meal image preserved in the example archive" width="1200" height="900"/><span className="small">FROM THE FAMILY ARCHIVE</span><h4>Photographs.<br/>Stories.<br/>Their own words.</h4></>}
 </aside>}
export function StoryShowcase({compact=false}:{compact?:boolean}){const [selected,setSelected]=useState(0);const p=panels[selected];return <div className={'story-showcase product-theater '+(compact?'compact-showcase':'')}><div className="product-tabs" role="group" aria-label="Explore A Story product designs">{panels.map((panel,i)=><button key={panel.id} aria-pressed={i===selected} onClick={()=>setSelected(i)}>{panel.label}</button>)}</div><div className="story-display" data-panel={p.id}><span className="display-counter" aria-label={'Design '+(selected+1)+' of 5'}>0{selected+1}<span>/ 05</span></span><div className="story-display-note" key={'text-'+p.id}><span className="eyebrow">A STORY / {p.id==='book'?'THE LONGER VIEW':'THE EXPERIENCE'}</span><h3>{p.title}</h3><p>{p.copy}</p></div><div className="theater-stage" key={p.id}><ContextCard id={p.id}/><figure className={'product-panel product-'+p.id}><img src={'/media/story/'+p.id+'.webp'} alt={p.id==='book'?'Teal A Story keepsake book concept':'Supplied A Story '+p.label+' product design'} width={p.id==='book'?700:530} height={p.id==='book'?950:1242} loading="lazy"/></figure><p className="theater-caption">{p.id==='book'?'Future keepsake concept':'Supplied product design · In development'}</p></div></div><p className="theater-disclosure">Illustrative product concept. Names and example memories are fictional.</p></div>}
