import {MediaFrame} from './MediaFrame';
import {SignalPath} from '../interactive/SignalPath';
import styles from './ThreeScenes.module.css';
function ArrowLink({href,children}:{href:string;children:React.ReactNode}){return <a href={href} className="text-link">{children}<span aria-hidden="true">→</span></a>}
export function Hero({candidate=false}:{candidate?:boolean}){
 return <section id="top" data-scene data-theme="cream" className={styles.hero} aria-labelledby="hero-title"><div className={`container ${styles.heroInner}`}>
  <p className={`eyebrow ${styles.heroLabel}`}>Engineer · Strategist · Builder</p>
  <h1 id="hero-title" className={styles.heroTitle}><span>From <em>silicon</em></span>{' '}<span>to strategy<span className={styles.period}>.</span></span></h1>
  <div className={styles.heroCopy}><p>{candidate?<>I build technical systems, then keep following the questions around them — from silicon and medical devices to strategy, and now <a href="/a-story">A Story</a>.</>:<>I work on difficult technology and the decisions that make it useful—from integrated circuits and medical devices to commercial strategy. Now I&apos;m building <a href="/a-story">A Story</a>, helping families preserve the stories of people they love.</>}</p>
   <div className={styles.heroActions}><ArrowLink href="/work">Explore my work</ArrowLink><ArrowLink href="/book">Open the book</ArrowLink></div><p className={styles.current}><i aria-hidden="true"/>Current chapter: <a href="/a-story">A Story</a></p></div>
  <MediaFrame id="portrait" className={styles.portrait} sizes="(min-width: 1280px) 300px, (min-width: 768px) 28vw, 62vw" priority/>
  <SignalPath className={styles.heroRoute} viewBox="0 0 220 320" d="M 0 20 H 84 V 94 H 180 V 274 H 100 L 100 312"/>
  <div className={styles.heroFoot}><a href="#silicon" className="text-link">Scroll to follow the signal <span aria-hidden="true">↓</span></a><span className="eyebrow">Vietnam → Michigan</span></div>
 </div></section>
}
export function Silicon(){return <section id="silicon" data-scene data-theme="blue" className={styles.silicon} aria-labelledby="silicon-title"><div className="container"><div className={styles.siliconGrid}>
 <div className={styles.siliconCopy}><p className="eyebrow">01 / Make it real</p><h2 id="silicon-title">Silicon.</h2><p className={styles.siliconStandfirst}>Tape-out puts a deadline on ambiguity.</p><p>At Faraday Technology, I worked on the test and timing flows that help make an ASIC ready for fabrication. That meant following the details through insertion, simulation, test-pattern delivery and timing sign-off—and coordinating when they did not line up.</p></div>
 <div className={styles.metrics}><div><strong>22 <span>nm</span></strong><p>UMC process used in the shuttle project</p><small>Source: Engineering résumé</small></div><div><strong>1.5 <span>months</span></strong><p>Timeline for a project I helped bring to tape-out</p><small>Source: Director&apos;s testimonial · April 2026</small></div></div>
 <div className={styles.workflow}><div className={styles.workflowTop}><p className="eyebrow">Test → Timing</p><span className="eyebrow">Faraday / 2024</span></div><ol><li><span>01</span><strong>DFT insertion</strong><small>Design for test</small></li><li><span>02</span><strong>Simulation &amp; <br/>test patterns</strong></li><li><span>03</span><strong>Timing sign-off</strong></li></ol><SignalPath className={styles.workflowRoute} duration={650} viewBox="0 0 600 140" d="M 30 30 H 190 V 100 H 370 V 30 L 570 30"/><p className={styles.workflowCaption}>Workflow schematic, based on documented responsibilities.</p></div>
 <div className={styles.faradayProof}><MediaFrame id="faraday" className={styles.faradayPhoto} sizes="(min-width: 1024px) 420px, (min-width: 768px) 40vw, calc(100vw - 40px)"/><div className={styles.proofLink}><span className="eyebrow">Faraday Technology<br/>Vietnam · 2024</span><ArrowLink href="/work/faraday-tapeout">Inside the work</ArrowLink></div></div>
 </div></div></section>}
export function Handoff(){return <div id="signal-handoff" data-scene data-theme="cream" className={styles.handoff}><div className={`container ${styles.handoffInner}`}>
 <p className={`eyebrow ${styles.handoffLabel}`}>A progression of questions, not a chronology.</p><div className={styles.transferType}><span>From silicon</span><span className="editorial">to stories.</span></div>
 <div className={styles.transferRail}><div className={styles.originLabels}><span>Circuits</span><span>Medical technology</span><span>Strategy</span></div><SignalPath className={styles.transferRoute} viewBox="0 0 600 320" from="M 168 34 L 228 34 L 228 94 L 300 94 L 300 154 L 376 154 L 376 258 L 558 258" d="M 168 34 L 252 34 L 252 86 L 578 86 L 578 266 L 298 266 L 298 126 L 558 126"><path d="M168 94H220V218H252 M168 154H196V242H252" stroke="currentColor" strokeOpacity=".3"/><path d="M274 98H566V254H274Z" fill="var(--paper)"/><path d="M298 126H318 M298 126V146 M558 126V146 M558 234H538 M558 234V214 M298 234H318 M298 234V214" stroke="currentColor" strokeOpacity=".5"/><circle cx="252" cy="86" r="4" fill="var(--soft)" stroke="currentColor"/></SignalPath><div className={styles.memoryType} aria-hidden="true"><span>Keep the voice.</span><span>Build the record.</span></div><p className={styles.destinationLabel}><span className="eyebrow">Current chapter</span><a href="#a-story">A Story <span aria-hidden="true">↓</span></a></p></div>
 </div></div>}
export function AStory({composition}:{composition:'a'|'b'}){return <section id="a-story" data-scene data-theme="cream" className={`${styles.story} ${composition==='b'?styles.storyB:styles.storyA}`} aria-labelledby="astory-title" data-composition={composition}><div className="container">
 <div className={styles.storyHeading}><p className="eyebrow"><i aria-hidden="true"/>Current chapter</p><h2 id="astory-title">A STORY</h2></div>
 <div className={styles.storyGrid}><div className={styles.archiveObject}>{composition==='b'&&<div className={styles.archiveIndex} aria-label="Conceptual archive structure"><span>Conversation</span><span>Memory</span><span>Archive</span></div>}<MediaFrame id="keepsake" className={styles.keepsake} sizes="(min-width: 1728px) 830px, (min-width: 1024px) 55vw, calc(100vw - 40px)"/>{composition==='b'&&<div className={styles.archiveMaterials} aria-hidden="true"><div className={styles.emptyMount}><i/><i/><i/><i/></div><div className={styles.paperNote}><span>Conversations.</span><span>Photographs.</span><span>Perspectives.</span></div><div className={styles.bindingLine}/></div>}</div>
 <div className={styles.storyCopy}><p className={`editorial ${styles.storyQuestion}`}>What if preserving a life story felt less like writing a memoir and more like having a good conversation?</p><p>I&apos;m co-founding A Story: a family archive built through conversation, photographs and the different ways people remember. We&apos;re developing the product and learning through pilots.</p><ArrowLink href="/a-story">Explore A Story</ArrowLink><p className={styles.storyRole}>Co-founder · Product strategy &amp; operations</p></div></div>
 </div></section>}
