import {chromium} from 'playwright';import AxeBuilder from '@axe-core/playwright';import fs from 'node:fs/promises';
async function main(){
 const out='qa/behavior';await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:900},recordVideo:{dir:`${out}/video`,size:{width:1440,height:900}}});const page=await context.newPage();const result:any={};
 await page.goto('http://127.0.0.1:3000/?composition=b');await page.evaluate(()=>document.fonts.ready);
 const signal=page.locator('#signal-handoff [data-signal]');await page.locator('#signal-handoff').evaluate(e=>scrollTo(0,e.getBoundingClientRect().top+scrollY-150));
 const frames=[];for(const pause of [50,150,200,500,300]){await page.waitForTimeout(pause);frames.push(await signal.evaluate(e=>({d:e.querySelectorAll('path')[4]?.getAttribute('d'),point:e.querySelector('circle:last-child')?.getAttribute('cx'),settled:e.getAttribute('data-settled')})));await page.screenshot({path:`${out}/signal-frame-${frames.length}.png`})}
 result.motionFrames=frames;await page.locator('#top').scrollIntoViewIfNeeded();await page.waitForTimeout(100);await signal.scrollIntoViewIfNeeded();await page.waitForTimeout(100);result.noReplay=await signal.getAttribute('data-settled')==='true';await page.waitForTimeout(500);
 const video=page.video();await context.close();if(video)await video.saveAs(`${out}/signal-handoff-1440.webm`);
 const testing=await browser.newContext();const p=await testing.newPage();result.menu=[];result.reflow=[];
 for(const width of [375,390,768]){
  await p.setViewportSize({width,height:844});await p.goto('http://127.0.0.1:3000');await p.evaluate(()=>document.fonts.ready);await p.locator('#silicon').scrollIntoViewIfNeeded();const before=await p.evaluate(()=>scrollY);const menuBox=await p.getByRole('button',{name:'Menu',exact:true}).boundingBox();if(!menuBox)throw new Error('Menu missing');await p.mouse.click(menuBox.x+menuBox.width/2,menuBox.y+menuBox.height/2);const closeFocus=await p.getByRole('button',{name:'Close menu'}).evaluate(e=>e===document.activeElement);let trapped=true;for(let i=0;i<16;i++){await p.keyboard.press('Tab');trapped&&=await p.evaluate(()=>!!document.activeElement?.closest('dialog'))}await p.screenshot({path:`${out}/menu-${width}.png`,animations:'disabled'});const axe=(await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations;await p.keyboard.press('Escape');await p.waitForTimeout(60);result.menu.push({width,closeFocus,trapped,returnFocus:await p.getByRole('button',{name:'Menu',exact:true}).evaluate(e=>e===document.activeElement),scrollPreserved:Math.abs((await p.evaluate(()=>scrollY))-before)<2,axe:axe.map(v=>v.id)});
 }
 for(const [width,height,textZoom] of [[320,900,false],[844,390,false],[390,844,true],[1440,900,true]] as const){
  await p.setViewportSize({width,height});await p.goto('http://127.0.0.1:3000/?composition=b');await p.evaluate(()=>document.fonts.ready);
  if(textZoom)await p.evaluate(()=>{const items=[...document.querySelectorAll<HTMLElement>('body *')].map(e=>({e,size:parseFloat(getComputedStyle(e).fontSize)}));for(const {e,size} of items)e.style.fontSize=`${size*2}px`});
  result.reflow.push({width,height,textZoom,overflow:await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),wideElements:await p.evaluate(()=>[...document.querySelectorAll('main *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,8).map(e=>({tag:e.tagName,cl:e.className,text:e.textContent?.slice(0,45)})))});
  await p.screenshot({path:`${out}/reflow-${width}-${height}${textZoom?'-text200':''}.png`,fullPage:true,animations:'disabled'});
  if(width===844||textZoom){await p.getByRole('button',{name:'Menu',exact:true}).isVisible().then(async visible=>{if(visible){await p.getByRole('button',{name:'Menu',exact:true}).click();await p.screenshot({path:`${out}/menu-${width}-${height}${textZoom?'-text200':''}.png`,animations:'disabled'});await p.keyboard.press('Escape')}})}
 }
 await p.emulateMedia({reducedMotion:'reduce'});await p.setViewportSize({width:390,height:844});await p.goto('http://127.0.0.1:3000/?composition=b');await p.locator('#signal-handoff').scrollIntoViewIfNeeded();await p.waitForTimeout(100);const reducedStart=await p.locator('#signal-handoff svg').innerHTML();await p.waitForTimeout(1000);result.reducedMotionStable=reducedStart===await p.locator('#signal-handoff svg').innerHTML();await p.locator('#signal-handoff').screenshot({path:`${out}/signal-reduced-390.png`,style:'header,.skip{visibility:hidden!important}'});
 const bAxe=(await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations;result.compositionBAxe=bAxe.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}));
 const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const n=await nojs.newPage();await n.goto('http://127.0.0.1:3000');result.noJs={headings:await n.locator('main h1, main h2').allTextContents(),prose:await n.locator('main').innerText(),images:await n.locator('main img').count()};await nojs.close();await testing.close();await browser.close();await fs.writeFile(`${out}/checks.json`,JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}main().catch(e=>{console.error(e);process.exitCode=1});
