const fs=require('fs');const p='components/BookReader.tsx';let s=fs.readFileSync(p,'utf8');
s=s.replace("type Mode='pages'", "function BookText({index,mode='pages'}:{index:number;mode?:string}){const c=bookChapters[index];return <><p className=\"eyebrow\">Chapter {String(index+1).padStart(2,'0')}</p><h2>{c.title}</h2>{c.id==='masters'&&<Photo className=\"book-mentor\" id=\"wentzloff\"/>}{(mode==='scroll'?c.paragraphs:c.paragraphs.slice(0,2)).map((p,j)=><p key={j}>{p}</p>)}<ArrowLink href={c.link}>{c.linkLabel}</ArrowLink><span className=\"book-folio\">{String(index*2+2).padStart(2,'0')} / The Path, So Far.</span></>;}\ntype Mode='pages'");
s=s.replace("const timers=useRef", "const modal=useRef<HTMLDialogElement>(null);\n const timers=useRef");
s=s.replace("const busy=phase!==", "const isVisible=phase!=='closed';\n useEffect(()=>{if(!isVisible)return;const dialog=modal.current;if(!dialog)return;const scrollY=window.scrollY,overflow=document.body.style.overflow;dialog.showModal();document.body.style.overflow='hidden';return()=>{dialog.close();document.body.style.overflow=overflow;window.scrollTo({top:scrollY,behavior:'instant'})}},[isVisible]);\n const busy=phase!==");
s=s.replace("},720)","},820)").replace("},680)","},720)");
s=s.replace('<div className="open-reader" ref={reader}', '<dialog className="book-modal" ref={modal} aria-label="The Path, So Far" onCancel={e=>{e.preventDefault();close()}}><div className="reader-opening-cover" aria-hidden="true"><BookCover/></div><div className="open-reader" ref={reader}');
s=s.replace('Open the Book ↗','Open the Book').replace('Read the scrolling story →','Read the scrolling story');
const textStart='<div className="book-right"><p className="eyebrow">Chapter {String(i+1).padStart(2,\'0\')}</p>';
const a=s.indexOf(textStart),b=s.indexOf('</div></article>',a);
if(a<0||b<0)throw Error('Book text boundary missing');
s=s.slice(0,a)+'<div className="book-right"><BookText index={i} mode={mode}/>'+s.slice(b);
const leafStart=s.indexOf('{(turn||drag>0||settling)&&<div className='), leafEnd=s.indexOf('</div>\n <div className="reader-controls">',leafStart);
if(leafStart<0||leafEnd<0)throw Error('Leaf boundary missing');
const leaf=`{(turn||drag>0||settling)&&<><div className={\`turn-static \${dragDirection===1?'hold-left':'hold-right'}\`} aria-hidden="true">{dragDirection===1?<div className="book-left"><p className="eyebrow">{bookChapters[ghost].year} / {bookChapters[ghost].label}</p><BookVisual id={bookChapters[ghost].id} index={ghost}/><span className="book-folio">{String(ghost*2+1).padStart(2,'0')} / Bao Vo</span></div>:<div className="book-right"><BookText index={ghost}/></div>}</div><div className={\`turning-leaf \${turn||(settling?'settling':'dragging')} \${dragDirection===-1?'from-left':''}\`} style={{'--turn-start':\`\${turnStart.current}deg\`,...(drag>0||settling?{transform:\`rotateY(\${dragDirection===1?-drag:drag}deg)\`}:{})} as React.CSSProperties} aria-hidden="true"><div className="leaf-front">{dragDirection===1?<div className="book-right"><BookText index={ghost}/></div>:<div className="book-left"><p className="eyebrow">{bookChapters[ghost].year} / {bookChapters[ghost].label}</p><BookVisual id={bookChapters[ghost].id} index={ghost}/><span className="book-folio">{String(ghost*2+1).padStart(2,'0')} / Bao Vo</span></div>}</div><div className="leaf-back">{dragDirection===1?<div className="book-left"><p className="eyebrow">{bookChapters[current].year} / {bookChapters[current].label}</p><BookVisual id={bookChapters[current].id} index={current}/><span className="book-folio">{String(current*2+1).padStart(2,'0')} / Bao Vo</span></div>:<div className="book-right"><BookText index={current}/></div>}</div><div className="paper-fold"/></div></>}`;
s=s.slice(0,leafStart)+leaf+s.slice(leafEnd);
s=s.replace('</button></div></div>\n <noscript>', '</button></div></div></dialog>\n <noscript>');
// Native dialog covers no-JS only after an explicit open; keep the fallback accessible.
s=s.replace('.book-theatre .closed-book,.book-theatre .open-reader{display:none!important}', '.book-theatre .closed-book,.book-theatre .book-modal{display:none!important}');
fs.writeFileSync(p,s);
