import fs from 'node:fs/promises';
const routes=[['a-story','A Story — A family archive, through conversation','Bao Vo’s current venture. Developing and piloting a family archive built through conversation, photographs, and multiple perspectives.'],['work','Selected work','Product, strategy, engineering and venture-building. Nine selected chapters from A Story to healthcare commercialization and real silicon work.'],['book','The Path, So Far — Interactive Book','A personal record in twelve chapters: Vietnam to Michigan, engineering, strategy, community, and co-founding A Story.'],['archive','Archive — Everything on the record','A searchable archive of Bao Vo’s product, strategy, engineering, research, teaching and community work, with reports and supporting exhibits.'],['about','About — From Vietnam to Michigan','Founder, strategist and builder. Bao Vo’s background in engineering, teaching, community at Michigan, and the path toward A Story.'],['contact','Contact','Talk with Bao Vo about ambitious products, difficult technology and commercial strategy. Email, LinkedIn and résumés.']];
async function main(){for(const [route,title,description] of routes){const file=`app/${route}/page.tsx`;let source=await fs.readFile(file,'utf8');source="import {pageMetadata} from '@/content/metadata';\n"+source.replace(/export const metadata=\{[^\n]+\};/,`export const metadata=pageMetadata(${JSON.stringify(title)},${JSON.stringify(description)},${JSON.stringify('/'+route)});`);await fs.writeFile(file,source)}
 const c=JSON.parse(await fs.readFile('content/case-copy.json','utf8'));
 const refinements:Record<string,[string,string,string]>={
 'faraday-tapeout':['The discipline behind a tape-out.','At Faraday Technology Vietnam, I worked on the test and timing flows that make an ASIC ready for fabrication. My contribution was at the delivery boundary: carrying a requirement through implementation, checking it, and making the handoff clear.','A deadline turns coordination into a concrete responsibility. The best handoff leaves the next person with something they can act on.'],
 'implantable-auditory-circuits':['A small circuit. A larger purpose.','My graduate research at Michigan focused on low-power circuits for a totally implantable auditory prosthesis. I worked at the interface between a physical sensor and the electronics that needed to preserve its information.','The research widened my interest beyond circuit performance. Manufacturing, adoption, and support became questions I wanted to understand alongside the design.'],
 'healthcare-commercialization':['A technology needs a reason to be adopted.','At miLEAD, I helped early-stage life-science teams examine the commercial choices around their technology: a first market, a target customer, or a reason to change direction. The work joined primary research with recommendations for leadership.','A finding earns its place in a recommendation when it changes the proposed action. I became more disciplined about making that connection explicit.'],
 articulate:['Another way to express a feeling.','ARTiculate was a team product concept exploring guided drawing for autistic children, with context parents and therapists could revisit. I served as Technical Architect and contributed to discovery, prototyping, and the competition pitch.','The first interaction is part of the product strategy. Technical feasibility matters only if the person being invited into the experience understands why they would begin.'],
 'aurora-market-entry':['Choose the market. Make the route credible.','For the 2026 Southeast Case Competition, I led Five Star Consulting’s recommendation for Aurora Sparkling Juices. We connected U.S. segment choice to supply options, capacity constraints, and a staged entry plan.','An attractive segment is only half a recommendation. The supply route and operating model have to make entry plausible.'],
 'cagrisema-launch-strategy':['Positioning is the start of a launch.','I led Syntria Partners’ CagriSema launch recommendation in the 2025 Midwest Healthcare Case Competition. The team considered portfolio positioning alongside access, provider engagement, and patient support.','A launch plan gets clearer when it identifies whose decisions need to change. Positioning, access, and support belong in the same discussion.'],
 'puf-security':['When variation becomes identity.','Our EECS 427 team compared ring-oscillator and SRAM physically unclonable functions: two ways to turn device variation into a repeatable chip identity. The choice ultimately depended on stability across changing conditions.','Additional functionality could not compensate for an unreliable identifier. The deciding criterion was dependability under the conditions the project needed to tolerate.'],
 'low-voltage-bandgap':['Holding a reference steady.','Our circuit-design team explored a low-voltage bandgap reference around a subthreshold operational amplifier. The project made the costs of low-power operation visible in stability, mismatch, startup, and layout.','Low power was a set of tradeoffs, not a single setting. Each improvement had to be weighed against the limits the reference could tolerate.'],
 };
 for(const item of c){const r=refinements[item.slug];item.title=r[0];item.intro=r[1];item.sections.find((s:any)=>s.label==='Reflection').paragraphs=[r[2]]}
 await fs.writeFile('content/case-copy.json',JSON.stringify(c,null,2));
 console.log('Route metadata and case-study framing finalized. Technical source detail retained.');
}main();
