import {chromium} from 'playwright';import AxeBuilder from '@axe-core/playwright';import fs from 'node:fs/promises';import {projects} from '../content/projects';
const base='http://127.0.0.1:3000';
async function main(){const browser=await chromium.launch({channel:'chrome',headless:true});const out='qa/ledger/final';await fs.mkdir(out,{recursive:true});const checks:any[]=[];const errors:string[]=[];const urls=['/','/a-story','/work','/book','/book?chapter=a-story&mode=pages','/archive','/about','/contact',...projects.filter(p=>p.href.startsWith('/work/')).map(p=>p.href)];
 for(const width of [390,1440]){for(const url of urls){const context=await browser.newContext({viewport:{width,height:width<500?844:1000},deviceScaleFactor:1});const page=await context.newPage();page.on('pageerror',e=>errors.push(`${width} ${url} ${e.message}`));const res=await page.goto(base+url);await page.waitForFunction(()=>document.documentElement.dataset.hydrated==='true');await page.evaluate(async()=>{await document.fonts.ready;document.querySelectorAll('img').forEach(i=>i.loading='eager');await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})))});const broken=await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>!(i as HTMLImageElement).naturalWidth).map(i=>(i as HTMLImageElement).src));const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();const slug=url==='/'?'home':url.replaceAll('/','-').replaceAll('?','-').replaceAll('=','-').replaceAll('&','-').slice(1);await page.screenshot({path:`${out}/${slug}-${width}.png`,fullPage:true});checks.push({width,url,status:res?.status(),overflow,broken,violations:axe.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});await context.close();console.log(width,url,overflow?'OVERFLOW':'ok',axe.violations.length);}}
 for(const width of [375,768,1728]){const page=await browser.newPage({viewport:{width,height:1000}});await page.goto(base);await page.waitForFunction(()=>document.documentElement.dataset.hydrated==='true');await page.evaluate(async()=>{await document.fonts.ready;document.querySelectorAll('img').forEach(i=>i.loading='eager');await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})))});await page.screenshot({path:`${out}/home-${width}.png`,fullPage:true});checks.push({width,url:'/',overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)});await page.close()}
 await fs.writeFile(`${out}/checks.json`,JSON.stringify({checks,errors},null,2));await browser.close();if(errors.length||checks.some(c=>c.overflow||c.broken?.length||c.violations?.length))process.exitCode=1;
}main();


