import {chromium} from 'playwright';import AxeBuilder from '@axe-core/playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {projects} from '../content/projects';
const base='http://127.0.0.1:3000';const out='qa/ledger/behavior';const results:Record<string,unknown>={};
async function main(){await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const consoleErrors:string[]=[];page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('pageerror',e=>consoleErrors.push(e.message));const go=async(url:string)=>{await page.goto(base+url);await page.waitForFunction(()=>document.documentElement.dataset.hydrated==='true')};
 await go('/book');await page.getByRole('button',{name:'Open the Book ↗',exact:true}).click();await page.waitForSelector('.reader-shell[data-open=true]');assert.match(page.url(),/chapter=origin/);await page.locator('.open-reader').focus();await page.keyboard.press('ArrowRight');await page.waitForSelector('.turning-leaf',{state:'hidden'});assert.match(page.url(),/chapter=materials/);await page.goBack();await page.waitForFunction(()=>document.querySelector('#chapter-origin')?.getAttribute('data-current')==='true');results.bookHistory=true;
 await page.locator('.reader-toolbar summary').click();await page.locator('.reader-toolbar nav button').nth(10).click();await page.waitForSelector('.turning-leaf',{state:'hidden'});assert.match(page.url(),/chapter=a-story/);await page.getByRole('button',{name:'View as scrolling story',exact:true}).click();assert.equal(await page.locator('.book-spread:visible').count(),12);await page.getByRole('button',{name:'View as pages',exact:true}).click();assert.equal(await page.locator('.book-spread:visible').count(),1);results.bookContentsAndScroll=true;
 await go('/book?chapter=real-silicon&mode=pages');await page.locator('.book-pages').scrollIntoViewIfNeeded();let r=(await page.locator('.book-pages').boundingBox())!;await page.mouse.move(r.x+r.width-15,r.y+180);await page.mouse.down();await page.mouse.move(r.x+r.width*.55,r.y+180,{steps:12});await page.mouse.up();await page.waitForSelector('.turning-leaf',{state:'hidden'});assert.match(page.url(),/chapter=medical-technology/);results.bookDrag=true;
 await page.locator('.open-reader').focus();await page.keyboard.press('End');await page.waitForSelector('.turning-leaf',{state:'hidden'});assert.equal(await page.getByRole('button',{name:'Next chapter →',exact:true}).isDisabled(),true);await page.keyboard.press('Home');await page.waitForSelector('.turning-leaf',{state:'hidden'});assert.equal(await page.getByRole('button',{name:'← Previous chapter',exact:true}).isDisabled(),true);results.bookBoundaries=true;
 await go('/a-story');await page.locator('.voice-tabs button').nth(1).click();assert.match(await page.locator('.voice-quotes').innerText(),/extra chair/);await page.getByRole('button',{name:'Read all perspectives',exact:false}).click();assert.equal(await page.locator('.voice-quotes blockquote').count(),3);await page.locator('.experience-object > nav button').nth(2).click();assert.match(await page.locator('.experience-paper').innerText(),/Put a memory in context/);results.storyInteractions=true;results.storyExpandedAxe=(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>v.id);await page.locator('.voices-object').screenshot({path:`${out}/voices-all-1440.png`});
 await go('/archive');await page.getByRole('searchbox').fill('PUF');assert.equal(await page.locator('.archive-record').count(),1);assert.match(page.url(),/q=PUF/);await page.getByRole('button',{name:'Clear filters',exact:true}).click();await page.getByLabel('Discipline',{exact:true}).selectOption('Engineering');const count=await page.locator('.archive-record').count();assert(count>=5);await page.goBack();await page.waitForFunction(()=>document.querySelectorAll('.archive-record').length===19);results.archiveSearchAndHistory=true;
 await go('/archive?category=Product#rf-front-end');await page.waitForSelector('#rf-front-end[open]');assert.equal(await page.locator('.archive-record').count(),19);results.archiveDeepLink=true;await page.locator('#rf-front-end').screenshot({path:`${out}/archive-open-1440.png`});
 await page.setViewportSize({width:390,height:844});await go('/');await page.getByRole('button',{name:'Menu',exact:false}).click();assert.equal(await page.locator('dialog[open]').count(),1);const first=page.getByRole('button',{name:'Close menu',exact:false});assert(await first.evaluate(e=>document.activeElement===e));await page.keyboard.press('Shift+Tab');assert(await page.locator('dialog').evaluate(e=>e.contains(document.activeElement)));results.menuAxe=(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>v.id);await page.screenshot({path:`${out}/mobile-menu-390.png`});await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);assert(await page.getByRole('button',{name:'Menu',exact:false}).evaluate(e=>document.activeElement===e));results.mobileMenu=true;
 await page.locator('.chapter-mobile summary').click();await page.locator('.chapter-mobile').getByRole('link',{name:'03 / Selected work'}).click();await page.waitForFunction(()=>location.hash==='#selected-work');assert.equal(await page.locator('.chapter-mobile[open]').count(),0);results.chapterJumps=true;
 for(const url of ['/','/a-story','/book?chapter=real-silicon&mode=pages','/archive','/about','/contact']){await page.setViewportSize({width:320,height:800});await go(url);assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),`320 overflow ${url}`)}results.reflow320=true;
 await page.emulateMedia({reducedMotion:'reduce'});await go('/book?chapter=origin&mode=pages');await page.locator('.open-reader').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('.turning-leaf').count(),0);assert.match(page.url(),/chapter=materials/);results.reducedMotion=true;
 const links=new Set<string>();for(const url of ['/','/a-story','/work','/book?mode=scroll','/archive','/about','/contact',...projects.filter(p=>p.href.startsWith('/work/')).map(p=>p.href)]){await go(url);for(const href of await page.locator('a[href]').evaluateAll(a=>a.map(a=>a.getAttribute('href')!).filter(h=>h.startsWith('/'))))links.add(href.split('#')[0]);}const brokenLinks=[];for(const href of links){const response=await context.request.get(base+href);if(response.status()>=400)brokenLinks.push({href,status:response.status()})}results.internalLinksChecked=links.size;results.brokenLinks=brokenLinks;assert.equal(brokenLinks.length,0);
 const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const fallback=await nojs.newPage();await fallback.goto(base+'/book');assert.equal(await fallback.locator('.book-spread:visible').count(),12);await fallback.goto(base+'/archive?q=PUF');assert.equal(await fallback.locator('.archive-record').count(),1);results.noJsBookAndArchive=true;await nojs.close();
 results.consoleErrors=consoleErrors;await fs.writeFile(`${out}/checks.json`,JSON.stringify(results,null,2));console.log(results);await browser.close();assert.equal(consoleErrors.length,0);assert.deepEqual(results.storyExpandedAxe,[]);assert.deepEqual(results.menuAxe,[]);
}main().catch(async e=>{await fs.writeFile(`${out}/partial.json`,JSON.stringify({...results,error:String(e)},null,2));console.error(e);process.exit(1)});

