const fs=require('fs');
let p='components/Home.tsx',s=fs.readFileSync(p,'utf8');s=s.replace(/<div className="hero-proof">.*?<\/div><\/div><\/section>/s,'</div></section>');fs.writeFileSync(p,s);
p='app/about/page.tsx';s=fs.readFileSync(p,'utf8').replace("['thinking','How I think']","['working','How I work']");s=s.replace(/ <section id="thinking".*?<\/section>/s,` <section id="working" className="section how-work"><span id="thinking" className="anchor-alias"/><div className="container"><Label>How I work</Label><div className="work-method-heading"><h2>Different problems.<br/><em>The same discipline.</em></h2><p>Tape-out, implantable circuits, consulting, and A Story ask different questions. Each starts with evidence and ends with a decision someone can use.</p></div><div className="work-methods"><article><span className="method-index">01</span><div><h3>Get close to the evidence.</h3><p>The timing path at <strong>Faraday</strong>. Noise and the physical sensor at <strong>WICS</strong>. Clinician interviews at <strong>miLEAD</strong>.</p></div><aside>Confidence should survive contact with the source.</aside></article><article><span className="method-index">02</span><div><h3>Find the constraint that matters.</h3><p>Power in an implantable circuit. Timing before tape-out. <strong>Trust in a family archive.</strong> The limiting factor changes the next decision.</p></div><aside>Power · Timing · Adoption · Trust</aside></article><article><span className="method-index">03</span><div><h3>Make the next move usable.</h3><p>An engineering handoff. A recommendation for biotech leadership. A first conversation in A Story. <strong>Give the next person something they can act on.</strong></p></div><aside>From analysis to a handoff.</aside></article></div></div></section>`);fs.writeFileSync(p,s);
p='components/MemoryDemo.tsx';s=fs.readFileSync(p,'utf8');const tail=s.slice(s.indexOf('const steps='));const head=`'use client';
import {useState} from 'react';
import {demoMemory,demoVoices as voices,demoDisclaimer} from '@/content/story-demo';
function VoiceCard({voice}:{voice:typeof voices[number]}){return <article className="perspective-card"><header><div><strong>{voice.name}</strong><span>{voice.role}</span></div></header><span className="small">{voice.detail}</span><blockquote>“{voice.quote}”</blockquote><aside><span className="small">{voice.attachment}</span><p>{voice.note}</p></aside></article>}
export function Voices(){const [shared,setShared]=useState(false);return <div className="shared-memory-demo voice-board" data-view={shared?'shared':'perspectives'}><header className="memory-event-header"><img src={demoMemory.image} width="1200" height="900" alt="The Sunday table shared by the example family’s accounts"/><div><span className="eyebrow">ONE EVENT / THREE VOICES</span><h3>{demoMemory.title}</h3><p>{demoMemory.subtitle}</p><span className="small">Eleanor · Daniel · Maya</span></div></header><div className="perspective-controls" role="group" aria-label="Memory perspectives"><button aria-pressed={!shared} onClick={()=>setShared(false)}>Perspectives</button><button aria-pressed={shared} onClick={()=>setShared(true)}>Shared memory</button></div><div className="perspective-stage" aria-live="polite"><div className="shared-record-reveal" aria-hidden={!shared}><div><article className="shared-event-record"><div><span className="eyebrow">IN THE FAMILY ARCHIVE</span><h4>{demoMemory.title}</h4><p>A Sunday meal. More chairs around the table. Three people who remember it differently.</p><div className="memory-tags"><span>Family gatherings</span><span>At Eleanor’s home</span><span>3 attached voices</span></div></div><aside><span className="small">APPROXIMATE PERIOD / 1998–99</span><h5>Both dates stay.</h5><p>Eleanor remembers 1998. Daniel’s album says 1999. The original accounts stay attached.</p></aside></article></div></div><div className="perspective-cards show-all">{voices.map(voice=><VoiceCard key={voice.name} voice={voice}/>)}</div></div><p className="concept-label">{demoDisclaimer}</p></div>}
`;
s=head+tail;s=s.replace(/<span>0\{i\+1\}<\/span>\{label\}/g,'{label}').replace(/<ol className="journey-progress".*?<\/ol>/s,'');s=s.replaceAll('SUNDAY AT HOME','SUNDAY AT ELEANOR’S').replaceAll('Sunday at home','Sunday at Eleanor’s').replaceAll('Mai','Eleanor').replaceAll('Linh','Daniel').replaceAll('An</strong>','Maya</strong>');s=s.replace('What do you remember about Sunday meals?','What do you remember about Sunday meals at Eleanor’s?').replace('Everyone arrived at a different time. We kept adding chairs.','I kept the dishes warm as everyone arrived. Daniel would bring another chair.');s=s.replaceAll('<span className="memory-avatar">M</span>','<span className="memory-avatar">E</span>').replaceAll('<span className="memory-avatar">L</span>','<span className="memory-avatar">D</span>').replaceAll('<span className="memory-avatar">A</span>','<span className="memory-avatar">M</span>');s=s.replace('SUNDAY AT ELEANOR’S / 0{step+1}','SUNDAY AT ELEANOR’S').replace('<h4>Making room<br/>at the table.</h4>','<h4>Sunday at Eleanor’s</h4><p className="memory-subtitle">Making room at the table.</p>');s=s.replace('<span>At home</span>','<span>At Eleanor’s home</span>');s=s.replace('</div></div></div>}','</div><p className="concept-label">{demoDisclaimer}</p></div></div>}');fs.writeFileSync(p,s);
p='app/a-story/page.tsx';s=fs.readFileSync(p,'utf8');s=s.replace(/<section id="conversation".*?<\/section>/s,`<section id="conversation" className="conversation starting-point blue section"><div className="container"><div><Label>A starting point</Label><h2>Most people won’t<br/>write a memoir.<br/><em>They will talk.</em></h2></div><div className="starting-support"><p><strong>A good question</strong> lowers the barrier. It gives memory somewhere to start.</p><p>Conversation makes room for spontaneity, detail, and disagreement in a way a blank page rarely does.</p></div></div></section>`);
s=s.replace(/<section id="pilots".*?<\/section>/s,`<section id="pilots" className="story-today blue section"><div className="container"><div className="today-opening"><Label>Where it stands today</Label><h2><span>Building.</span><span>Testing.</span><em>Refining.</em></h2><p>A Story is in active development. Early pilots help us understand what makes people begin—and what makes them come back.</p></div><div className="today-evidence"><article><span className="eyebrow">ACTIVE DEVELOPMENT</span><h3>Make the first experience work.</h3><p>Product decisions start with a conversation worth saving.</p></article><article><span className="eyebrow">EARLY PILOTS</span><h3>Four nursing homes.</h3><p>Early testing brings the product into real care settings.</p></article><article className="today-question"><span className="eyebrow">THE QUESTION WE KEEP TESTING</span><h3>After the first conversation,<br/><em>does someone want to come back?</em></h3></article></div><div className="today-role"><div><span className="eyebrow">BAO VO / CO-FOUNDER & COO</span><p>Product · Operations<br/>Pilots & partnerships · Commercialization</p></div><div className="today-actions"><ArrowLink className="solid-link" href="/contact?topic=a-story">Talk with me about A Story</ArrowLink><ArrowLink className="outline-link" href="#experience">See the product journey</ArrowLink></div></div></div></section>`);
s=s.replace('className="story-ending blue"','className="story-ending story-final-note"');fs.writeFileSync(p,s);
p='components/ScrollMotion.tsx';s=fs.readFileSync(p,'utf8').replace('.contact-layout\'',".contact-layout,.story-today .today-opening,.story-today .today-evidence,.story-today .today-role'");fs.writeFileSync(p,s);
p='app/layout.tsx';s=fs.readFileSync(p,'utf8').replace("import './quality.css';","import './quality.css';\nimport './precision.css';");fs.writeFileSync(p,s);
