import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';import {gzipSync} from 'node:zlib';import media from '../content/media-data.json';
async function main(){
 const root=process.cwd().replaceAll('\\','/');const files=(await fs.readdir('qa/final')).filter(f=>f.endsWith('.png')).sort();
 let index='# Gate 3 screenshot index\n\nFinal production captures · 12 September 2026. Isolated scene captures hide sticky navigation to avoid stitching it through the middle of a long scene; viewport and boundary captures retain the actual header. Widths are CSS pixels. Heights: 844 mobile, 1024 tablet, 900 desktop.\n\n';
 for(const width of [375,390,768,1440,1728]){index+=`## ${width}px\n\n`;for(const f of files.filter(f=>f.endsWith(`-${width}.png`)))index+=`- [${f}](<${root}/qa/final/${f}>)\n`;index+='\n'}
 index+=`## Interaction and navigation\n\n- [Signal handoff recording](<${root}/qa/behavior/signal-handoff-1440.webm>)\n- [Reduced-motion resting state](<${root}/qa/behavior/signal-reduced-390.png>)\n- [Keyboard/reflow results](<${root}/qa/behavior/checks.json>)\n- [Gate 2 shell checks](<${root}/qa/gate2/checks.json>)\n- [Performance results](<${root}/qa/performance/checks.json>)\n\nEarlier comparisons are retained under qa/r1 and qa/r2. The original r1 Signal was rejected before additional routes were considered.\n`;
 await fs.writeFile('qa/SCREENSHOT_INDEX.md',index);
 const sources:string[]=[];async function walk(dir:string){for(const item of await fs.readdir(dir,{withFileTypes:true})){const name=path.join(dir,item.name);if(item.isDirectory())await walk(name);else if(/\.(tsx?|css|json)$/.test(name))sources.push(name)}}await walk('app');await walk('components');await walk('content');sources.push('package.json','pnpm-lock.yaml','next.config.ts');
 const records=[];for(const f of sources.sort())records.push({path:f.replaceAll('\\','/'),sha256:createHash('sha256').update(await fs.readFile(f)).digest('hex')});
 const customChunks=[];for(const f of await fs.readdir('.next/static/chunks'))if(f.endsWith('.js')){const code=await fs.readFile(`.next/static/chunks/${f}`,'utf8');if(code.includes('data-signal')||code.includes('Site navigation')||code.includes('inset(0 100% 0 0)'))customChunks.push({file:f,gzipBytes:gzipSync(code).length})}
 const html=await (await fetch('http://127.0.0.1:3000')).text();const forbidden=['a-story-company-memo','source-text/','nursing-home-pilot-photo','astory_album_1952','Drop a real headshot'];
 const report={revision:'Gate 3 final',buildId:(await fs.readFile('.next/BUILD_ID','utf8')).trim(),sources:records,sourceDigest:createHash('sha256').update(JSON.stringify(records)).digest('hex'),screenshotCount:files.length,customChunks,customGzipBytes:customChunks.reduce((n,c)=>n+c.gzipBytes,0),privateTermsInHtml:forbidden.filter(s=>html.includes(s)),media:media.filter(m=>m.publication==='public').map(m=>({id:m.id,source:m.source,largestAvifBytes:Math.max(...m.derivatives.filter(d=>d.format==='avif').map(d=>d.bytes))}))};
 await fs.writeFile('qa/production-revision.json',JSON.stringify(report,null,2));console.log({...report,sources:`${records.length} hashed files`});
}main().catch(e=>{console.error(e);process.exitCode=1});
